### ISSUE TITLE
Gather everyone on Zenhub

### ISSUE THREAD

**Issue by greenson** [nyu-devops-fall19-suppliers/suppliers#1]
**As a** Product Owner
**I need** our team to use Zenhub pipelines
**So that** we could create new issues and prioritize them

**Assumptions:**
* It seems like Zenhub does not support Github username searching...
![](https://i.imgur.com/5TyBUG1.png)
So please let me know your email that is linked to Zenhub (via Slack)
Thanks!

**Acceptance Criteria**
```
When I receive the email, and I send the invitation
Then everyone should be able to use Zenhub for our project
```

**Comment by Krystal-158** [comment]
Mine is yb1059@nyu.edu

**Comment by lhmartin** [comment]
mine is lukechile@gmail.com
