### ISSUE TITLE
Write BDD Test for Delete Operation

### ISSUE THREAD

**Issue by silemie** [nyu-devops-fall19-suppliers/suppliers#117]
**As a** developer
**I need** BDD testing
**So that** we can run automated testing 

**Assumptions:**
* ...

**Acceptance Criteria**
```
Given a RESTful app 
When running the command line `behave`
Then testing Delete operation
```

**Comment by lhmartin** [comment]
This test is failing, I don't know why it is failing. As this is not consistent with what is written in service.py. anyone know why this is failing?

<img width="728" alt="Screenshot 2019-11-20 at 15 13 13" src="https://user-images.githubusercontent.com/16001690/69274466-667b7680-0ba8-11ea-8962-a8da3a269bd1.png">
