### ISSUE TITLE
Create a Burndown chart

### ISSUE THREAD

**Issue by lhmartin** [nyu-devops-fall19-suppliers/suppliers#15]
**As** the Scrum Master
**I need** to be able to track team progress
**So that** I can monitor how fast we are progressing

**Assumptions:**
* We will assign story points and monitor progress through a burndown chart for each sprint

**Acceptance Criteria**
```
Given that open our Zenhub board
When I go to reports
Then I see a burndown chart for the sprint
```

**Comment by lhmartin** [comment]
@greenson Can you check that the burndown chart works for you?

**Comment by greenson** [comment]
> @greenson Can you check that the burndown chart works for you?

It looks good, nice work!
I am closing this issue then.
