### ISSUE TITLE
Discuss and Choose a Database 

### ISSUE THREAD

**Issue by lhmartin** [nyu-devops-fall19-suppliers/suppliers#20]
**As a** developer
**I need** to know what database we will use
**So that** we can continue development

**Assumptions:**
* We will some form of a database for this project

**Acceptance Criteria**
```
Given that we have discussed our options for databases 
When we have come to a conclusions
Then edit this story to serve as documentation of the results of the discussion
```

**Comment by lhmartin** [comment]
I have some experience with SQL, however, I am interested in what database systems everyone else has some experience working with?

**Comment by greenson** [comment]
I have experiences on both SQL and NoSQL, so these two DBMS both work for me. 

For this RESTful API project, I personal prefer NoSQL actually, that some of which like MongoDB provides a naive JSON interface to data and has a very rich query language. 

It should be pretty easy to pick up. However, if anyone prefers to use SQL that you are familiar with, I am okay with it as well.

**Comment by Krystal-158** [comment]
I have some experience in SQL and Hbase(NoSQL), and I agree with Greenson because NoSQL is more scalable. I also find some other teams use MongoDB, which we can keep as an option.

**Comment by lhmartin** [comment]
Okay sounds like a NoSQL database is the way to go, should we go with @greenson 's suggestion of MongoDB?

**Comment by greenson** [comment]
Scrum master @silemie, what do you think of it?

**Comment by silemie** [comment]
I have some experience in MySQL. I agree with @greenson to use NoSQL database for RESTful API. How about MongoDB?

**Comment by Krystal-158** [comment]
MongoDB sounds good for me. Then let's use MongoDB, shall we?

Sile <notifications@github.com>于2019年10月5日 周六18:49写道：

**Comment by greenson** [comment]
Cool! I am down with it. 

Here is a tutorial that I found really helpful when I did my previous MongoDB project for the first time. Feel free to have a look :D
[https://www.tutorialspoint.com/mongodb/mongodb_data_modeling.htm]()

Maybe we can start with setting up MongoDB environment?

**Comment by silemie** [comment]
Sure, we can. Let's create a setup MongdoBD story first.

**Comment by lhmartin** [comment]
Okay cool, so we can update this story to show that we are using MongoDB and then close it?
