### ISSUE TITLE
Suppliers data schema design

### ISSUE THREAD

**Issue by greenson** [nyu-devops-fall19-suppliers/suppliers#21]
**As a** developer
**I need** to know what our database will be look like
**So that** we can define and implement our actual database.

**Assumptions:**
* It should contain information about the supplier, and a collection of references to the products
that they provide. Its may also include the wholesale price of the products.

**Acceptance Criteria**
```
Given that we have discussed our data schema for databases 
When we have come to a conclusions
Then the proposed data schema should be documented in the repo README.md
```

**Comment by Krystal-158** [comment]
Here is a possible suppliers' JSON format:
{
  "supplier ID": "<int>",
  "supplier name": "<string>",
  "address": "<string>",
  "product category": "<string>"
  "average rating": "<float>",
}

Leave comments if you have any thoughts or come up with some other fields in JSON.

**Comment by Krystal-158** [comment]
I did not include much product info. 
One consideration is that product info should be kept in product resources, and how products match with suppliers should be maintained in another table, which is beyond our job. 
Another consideration is that we could be blocked by other teams' process if we depend on their resources.
What do you guys think of this?

**Comment by greenson** [comment]
Added type info and "wholesale price" attribute to Krystal's JSON schema:
<pre>{
  supplierID: {
    type: String,
    required: 'Missing ID'
  },
  supplierName: {
    type: String,
    required: 'Missing name'
  },
  "address":  {
    type: String,
    required: 'Missing address'
  },
  "productCategory": {
    type: String,
    required: 'Missing category'
  },
  "averageRating": {
    type: Number,
    required: 'Missing average rating'
  },
  wholesalePrice: {
    type: Number,
    required: 'Missing wholesale price'
  }
}</pre>

**Comment by lhmartin** [comment]
In the assignment description our brief is: "[Suppliers] should contain information about the supplier, and a **collection of references** to the products that they provide. It may also include the wholesale price of the products. Since this is really a
collection of product items, you will need to implement a **subordinate API to associate products**
into the supplier's collection" So it seems like we will need to at least collaborate with the products group to build this collection. We will then also have to add a "products" element

**Comment by Krystal-158** [comment]
Final format:

{
  supplierID: {
    type: String,
    required: 'Missing ID'
  },
  supplierName: {
    type: String,
    required: 'Missing name'
  },
  address:  {
    type: String,
    required: 'Missing address'
  },
  productIdList: {
    productID{
       type: Number,
       required: 'Missing average rating'
       },
  },
  averageRating: {
    type: Number,
    required: 'Missing average rating'
  },
}
