### ISSUE TITLE
Write a create operation

### ISSUE THREAD

**Issue by Krystal-158** [nyu-devops-fall19-suppliers/suppliers#3]
**As a** user
**I need** to be able to create a supplier
**So that** I can enter in new suppliers

**Assumptions:**
* 

**Acceptance Criteria**
```
Given I call 'POST /suppliers'
and I should get confirmation with the new supplier that has been added
```

**Comment by greenson** [comment]
Hi @Krystal-158 I didn't find the code of create operation, could you please point it out to me?

Also, I don't think we should use a create operation by posting to 'suppliers/ID' as we are not suppose to know the auto-generated ID of that document before creation.

Instead, it would look like this:
[https://i.imgur.com/M6MEO89.png](https://i.imgur.com/M6MEO89.png)

**Comment by Krystal-158** [comment]
@greenson  It is at the line 98 in /service/service.py: create_suppliers. some of the codes are commented because it is in the process of testing when I submitted it....
Because the service tests always throw errors, I don't think the whole function works running in the Postman. But with part of the function, it looks like:
<img width="811" alt="屏幕快照 2019-10-14 15 21 06" src="https://user-images.githubusercontent.com/26925638/66777471-1ae1f880-ee97-11e9-9f8f-0aeea7ff1229.png">

**Comment by Krystal-158** [comment]
I did not take care of ID manually, as it will be assigned a random ID upon insertion.

**Comment by greenson** [comment]
Very cool!

As for the ID stuff I mentioned, it's about the Acceptance Criteria in this issue description. I am correcting it right away 🗡 

Good job!
