### ISSUE TITLE
Setup MongoDB Environment 

### ISSUE THREAD

**Issue by silemie** [nyu-devops-fall19-suppliers/suppliers#39]
**As a** scrum master
**I need** the API work with a proper database environment
**So that** we can use MongoDB

**Assumptions:**
* We use MongoDB as a database

**Acceptance Criteria**
```
Given that `git clone` and ssh to the VM 
When I type the command "docker exec -it mongodb bash"
Then the mongodb interactive bash should be working
```

**Comment by greenson** [comment]
Some useful links on loading docker applications inside a VM:
[https://www.vagrantup.com/docs/provisioning/docker.html]()
[https://hub.docker.com/_/mongo](url)
