### ISSUE TITLE
Install a Flask MongoDB library to connect the database with a Flask app

### ISSUE THREAD

**Issue by greenson** [nyu-devops-fall19-suppliers/suppliers#42]
We have chosen PyMongo

**As a** developer
**I need** a Flask library that supports MongoDB 
**So that** I can connect the database with a Flask app

**Assumptions:**
* Flask-PyMongo - https://flask-pymongo.readthedocs.io/en/latest/
* Flask-MongoAlchemy - https://pythonhosted.org/Flask-MongoAlchemy/
* Flask-MongoEngine - http://docs.mongoengine.org/projects/flask-mongoengine/en/latest/

**Acceptance Criteria**
```
Given that I ssh into the VM
When I require some data via the Flask app
Then I should fetch the data from the established MongoDB database
```

**Comment by lhmartin** [comment]
I vote for PyMongo!

**Comment by silemie** [comment]
Vote for PyMongo too :D

**Comment by greenson** [comment]
Vote for PyMongo as well :)

**Comment by Krystal-158** [comment]
Then let's use PyMongo.

**Comment by greenson** [comment]
I came across an issue with PyMongo, that I could not find a built-in function in PyMongo supporting data schema define and data validation. 

However, the MongoEngine seems to support that. [https://realpython.com/introduction-to-mongodb-and-python/#defining-a-document](url)

Since data validation can be a pretty important part (e.g. we don't want an array list to be put into a string field), should we consider switch to MongoEngine instead?

**Comment by silemie** [comment]
Sure. If MongoEngine is better in the validation

**Comment by lhmartin** [comment]
Agreed, should be no problem to switch this early.

**Comment by silemie** [comment]
We change to MongoEngine
