### ISSUE TITLE
Add tests to ensure the coverage of tests over 95%

### ISSUE THREAD

**Issue by Krystal-158** [nyu-devops-fall19-suppliers/suppliers#75]
**As a** developer
**I need** to ensure the testing coverage over 95%
**So that** make the code solid and robust.

**Assumptions:**
*  We use ```coverage report -m``` to check the testing coverage

**Acceptance Criteria**
```
Given well working code
When we call command 'nosetests'->'coverage report -m'
Then the average coverage should be over 95%
```

**Comment by lhmartin** [comment]
I think this kinda a big ask for one person, we probably should all be working on this? @Krystal-158  @greenson  @silemie ?

**Comment by greenson** [comment]
Agree. Maybe we can chunk down this big task into small pieces and assign them to each individual?

**Comment by silemie** [comment]
Agree. @Krystal-158 which operation are you working now?

**Comment by Krystal-158** [comment]
> Agree. Maybe we can chunk down this big task into small pieces and assign them to each individual?

**Comment by silemie** [comment]
BTW I see there is an error in delete_a_supplier 
Error code:
`TypeError: delete() missing 1 required positional argument: 'supplier_id'`

**Comment by Krystal-158** [comment]
Yes, and I also met two import errors caused by importing mongoengine.errors

**Comment by lhmartin** [comment]
<img width="913" alt="Screenshot 2019-10-15 at 23 52 25" src="https://user-images.githubusercontent.com/16001690/66886863-e9585280-efa6-11e9-9aa4-bba13107e545.png">


Here is our line-by-line coverage. We should comment on this issue and say what lines we will be tackling, and go fix it

**Comment by Krystal-158** [comment]
models 61-62 fixed

**Comment by Krystal-158** [comment]
models 89-90 fixed

**Comment by Krystal-158** [comment]
I guess find_by_product do not need to raise any ValidationError or other errors, because we cannot predict which product never exists in our product lists, and the query will return an empty list if no suppliers match.

**Comment by Krystal-158** [comment]
models.py test coverage reaches 98%.
