### ISSUE TITLE
Write query operation

### ISSUE THREAD

**Issue by Krystal-158** [nyu-devops-fall19-suppliers/suppliers#8]
**As a** developer
**I need**  a function to be able to query the existed data
**So that** we can look up the database in formatted way

**Assumptions:**
* We are developing a RESTful API that has query functionanlity
* We are creating tests for each actions

**Acceptance Criteria**
```
Given that I run the server
When I access the API via HTTP.QUERY
Then I should get information from database
```

**Comment by greenson** [comment]
This issue is for the query_by_name function in the **model.py**, not the query router in the **service.py**. Confusion resolved with @silemie , closing this issue.
