### ISSUE TITLE
Delete old/unneeded branches

### ISSUE THREAD

**Issue by lhmartin** [nyu-devops-fall19-suppliers/suppliers#80]
**As a** developer
**I need** trim the branches on the git repo
**So that** I can more easily mange them

**Assumptions:**
* We desire to have a few numbers of active branches at once

**Acceptance Criteria**
```
Given that I look at the active branhces
Then I will see only actively used branches 
```

**Comment by silemie** [comment]
Thanks for the reminder!
I've already deleted queryTest. Still waiting for approval of actionTest branch
