### ISSUE TITLE
Create a Python Flask Cloud Foundry application in IBM Cloud

### ISSUE THREAD

**Issue by Krystal-158** [nyu-devops-fall19-suppliers/suppliers#99]
**As a** developer
**I need** a cloud based python environment
**So that** I can deploy the python flask app to the cloud

**Assumptions:**
* We will be using IBM cloud 
* We will be using a Python Cloud Foundry app
* We use the name: nyu-suppliers-service-f19 on .mybluemix.net

**Acceptance Criteria**
```
Given that I login to cloud.ibm.com and switch to Luke's profile
When I look at the Resource List
Then I should see a python buildpack cloud foundry app running on **nyu-suppliers-service-f19**
```

**Comment by lhmartin** [comment]
@greenson  @Krystal-158  @silemie  Can you guys confirm that you all can access this please

**Comment by greenson** [comment]
This is the Resource List after I switched to your IBM account.
![image](https://user-images.githubusercontent.com/17645845/68628824-ba52d500-04af-11ea-85f5-429f0d46f1a1.png)
Am I doing the right way?

**Comment by lhmartin** [comment]
Found the solution in the slack channel, have to assign you all direct access to cloud foundry. please check again in like 5 minutes

**Comment by greenson** [comment]
Cheers mate! I can see our app now, well done!
